version: "3"
services:
  test-suite:
    image: klieber/jmp-build
    command: ./build.sh
    working_dir: /project
    volumes:
      - .:/project
      - mvn-home:/root/.m2
      - bundle:/root/.bundle
    environment:
      - BUNDLE_PATH=/root/.bundle
    stdin_open: true
    tty: true
    ports:
      - "8234:8234"
    privileged: true
volumes:
  mvn-home:
  bundle:
