name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: 'This issue has been marked as stale because it has not been updated in 60 days. Please add a comment or this will be closed in 7 days.'
          stale-pr-message: 'This pull request has been marked as stale because it has not been updated in 60 days. Please add a comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no updates.'
          close-pr-message: 'This pull request was closed because it has been stalled for 7 days with no updates.'
          exempt-issue-labels: 'work-in-progress'
          exempt-pr-labels: 'work-in-progress,dependencies'
          only-labels: 'awaiting-feedback,awaiting-answers,more_info_requested'
